# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9984b663fffb65f8bd9252df36332c0e2d235a74415d05e5499cf9949b003dd776677d2ef2267148a5b1992c9f8809617822a6592b5e1f1fa05e9f7550a82541

test:
  secret_key_base: 182853b10bc8e5dff8b36adcaea42d3c97e176a1b01226ea95fcb9aa20bbdbb63aaa147cd2c62215028514bf63a293b49c53aac5b64338d30cf7ed72e60bd578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
